# Generated by Django 3.2.14 on 2022-08-21 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('createdBy', models.CharField(max_length=100)),
                ('content', models.TextField(default='None', max_length=1000)),
                ('timestamp', models.CharField(default='None', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(default='None', max_length=1000)),
                ('completed', models.BooleanField(default=False)),
                ('status', models.CharField(default='ToDo', max_length=50)),
                ('timestamp', models.CharField(default='None', max_length=100)),
                ('priority', models.CharField(default='None', max_length=10)),
                ('dateToComplete', models.CharField(default=False, max_length=100)),
                ('createdBy', models.CharField(default='None', max_length=100)),
                ('projectID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectID', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='None', max_length=1000)),
                ('createdBy', models.CharField(default='None', max_length=100)),
                ('ticketID', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ticketID', to='api.ticket')),
            ],
        ),
    ]
