# Generated by Django 3.2.14 on 2022-07-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='content',
            field=models.TextField(default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='ToDo', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
