# Generated by Django 3.2.14 on 2022-07-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220729_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timestamp',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
