# Generated by Django 3.2.14 on 2022-08-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220805_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='createdBy',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
